OrdererOrgs:
  - Name: Orderer
    Domain: hyperledgerOrderer.server.bjoola.nl        # Do localhost for now, will need a domain for the organisation later
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Vrendly
    Domain: hyperledgerOrg1.server.bjoola.nl
    Template:
      Count: 1
    Users:
      Count: 2
  - Name: Digitalefactuur
      Domain: hyperledgerOrg2.server.bjoola.nl
      Template:
        Count: 1
      Users:
        Count: 2
  - Name: Notbetalen
      Domain: hyperledgerOrg3.server.bjoola.nl
      Template:
        Count: 1
      Users:
        Count: 2
