OrdererOrgs:
  - Name: Orderer
    Domain: localhost        # Do localhost for now, will need a domain for the organisation later
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Vrendly
    Domain: vrendly.localhost
    Template:
      Count: 1
    Users:
      Count: 2
  - Name: Digitalefactuur
      Domain: digitalefactuur.localhost
      Template:
        Count: 1
      Users:
        Count: 2
  - Name: Notbetalen
      Domain: notbetalen.localhost
      Template:
        Count: 1
      Users:
        Count: 2
